name: Validate Cloudflare Pages deployment
description: Validate Cloudflare Pages deployment

inputs:
  github-token:
    description: GitHub token
    required: false
  max-attempts:
    description: Maximum number of attempts
    required: false
    default: '9'
  interval-seconds:
    description: Interval between attempts in seconds
    required: false
    default: '15'

runs:
  using: 'composite'
  steps:
    - name: Wait for Cloudflare Pages deployment
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github-token || github.token }}
        script: |
          const waitForCloudflarePagesDeployment = require('${{ github.action_path }}/wait-cf-pages-deployment.cjs');
          await waitForCloudflarePagesDeployment({
            github,
            context,
            core,
            maxAttempts: parseInt('${{ inputs.max-attempts }}', 10),
            intervalSeconds: parseInt('${{ inputs.interval-seconds }}', 10),
          });
