name: Actionlint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  action-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: jabranr/workflows/.github/actions/actionlint@main