name: Reusable Lighthouse Performance

on:
  workflow_call:
    inputs:
      urls:
        description: 'Comma-separated list of URLs to audit'
        type: string
        required: true
      save-artifact:
        description: 'Save the Lighthouse report as an artifact'
        type: boolean
        required: false
        default: false
    secrets:
      inherit: true

permissions:
  contents: read

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Run Lighthouse
        uses: foo-software/lighthouse-check-action@master
        with:
          urls: ${{ inputs.urls }}
          gitAuthor: ${{ github.actor }}
          gitBranch: ${{ github.ref }}
          gitHubAccessToken: ${{ secrets.GITHUB_TOKEN }}
          outputDirectory: '${{ github.workspace }}/tmp/artifacts'

      - name: Create artifacts directory
        if: ${{ inputs.save-artifact }}
        run: mkdir -p "${{ github.workspace }}/tmp/artifacts"

      - name: Upload Lighthouse artifacts
        if: ${{ inputs.save-artifact }}
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-results
          path: '${{ github.workspace }}/tmp/artifacts'
